---
title: "Markdown file"
author: "Marissa Freed"
date: "4/30/2018"
output: 
  html_document:
    code_folding: hide
    df_print: paged
    fig_width: 10
    fig_length: 8
    theme: lumen
    fig_caption: true
---

```{r setup, include = FALSE}
library(tidyverse)
library(mdsr)
library(RMySQL)
library(data.table)
imdb <- dbConnect_scidb(dbname = "imdb")
```


```{r first filters, warning=FALSE, message=FALSE}
gendergross <- imdb %>%
  dbGetQuery("SELECT n.name as actor, gender, person_id, ci.movie_id, person_role_id as char_id,  cn.name as character_name, title, production_year, mi.info as language, mi2.info as gross
from imdb.name n
join imdb.cast_info ci on n.id = ci.person_id
join imdb.char_name cn on cn.id = ci.person_role_id
join imdb.title t on t.id = ci.movie_id
JOIN imdb.movie_info mi ON mi.movie_id = ci.movie_id
JOIN imdb.movie_info mi2 ON mi2.movie_id = ci.movie_id
WHERE mi.info_type_id IN (4) AND mi.info = 'English'
  AND kind_id = 1
  AND mi2.info_type_id = 108 AND mi2.info like '%(USA%'
  and production_year > 1999
ORDER BY title;")
#join actor names to their characters, character names, the titles of the films, as well as language of films, and all films with opening weekend box office gross data. then filter for just English films premiering in the USA after 1999 (so only 21st century).

english_table <- imdb %>%
  dbGetQuery("SELECT t.id, title, kind_id, production_year, movie_id, info_type_id, info AS language
FROM imdb.title t 
join imdb.movie_info m on t.id = m.movie_id
having kind_id = 1 
and info like '%English%'
and production_year > 1999
and info_type_id = 4;")
#join title of films to movie.info to filter out non-english films

gross_table <- imdb %>%
  dbGetQuery("SELECT t.id, title, kind_id, production_year, info_type_id, info
FROM imdb.title t 
join imdb.movie_info m on t.id = m.movie_id
having kind_id = 1 
and production_year > 1999
and info_type_id = 108
and info like '%USA%';")
#join same as above but filtering USA opening weekend box office grosses 

votes_table <- imdb %>%
  dbGetQuery("SELECT t.id, t.title, t.production_year, 
  miv.info AS votes
FROM title t
JOIN movie_info_idx AS miv ON miv.movie_id = t.id
WHERE t.kind_id = 1
  AND miv.info_type_id = 100
  AND miv.info > 50000;")
#join title and movie info to find films with 100k + votes on IMDb

ratings_table <- imdb %>%
  dbGetQuery("SELECT t.id, t.title, t.production_year, mir.info AS rating
FROM title t
JOIN movie_info_idx AS mir ON mir.movie_id = t.id
WHERE t.kind_id = 1
  AND mir.info_type_id = 101;")
#find ratings for films

```

```{r, warning=FALSE, message=FALSE}
gendergross <- gendergross %>%
  mutate(gross_string = str_extract(gross, "^\\$[0-9]+,[0-9]{3},[0-9]{3}"),
         gross_numeric = parse_number(gross_string)) %>% #Used regular expressions to create a new column where gross is a numeric vector
  filter(grepl("\\(USA\\)", gross)) %>% #Used regular expressions to filter the info column to movies opening in the USA
  arrange(desc(gross_numeric))


char_total <- gendergross %>%
  group_by(movie_id) %>%
  summarize(total_people = n_distinct(char_id)) #find total number of actors listed for each movie

gender_total <- gendergross %>%
  group_by(movie_id, gender) %>%
  summarize(gendertot = n_distinct(char_id)) %>% #find total number of actors listed for each movie by gender
  full_join(char_total, by = "movie_id") #join with char_total to get column with total actors for each moview

gender_total1 <- gender_total %>%
  filter(gender == 'f') %>%
  group_by(movie_id) %>%
  mutate(ratiof = gendertot/total_people) #create column with the ratio of women to men for each movie
```

```{r, warning=FALSE, message=FALSE}
joined_gross <- gross_table %>%
  inner_join(english_table, by = c("id", "title", "kind_id", "production_year")) %>% #join table showing english movies with table showing gross
  mutate(gross_string = str_extract(info, "^\\$[0-9]+,[0-9]{3},[0-9]{3}"),
         gross_numeric = parse_number(gross_string)) %>% #Used regular expressions to create a new column where gross is a numeric vector
  filter(grepl("\\(USA\\)", info)) %>% #Used regular expressions to filter the info column to movies opening in the USA
  filter(grepl("screens\\)", info)) %>% #Used regular expressions to filter the info column to ones that show how many screens the movie was shown on in the opening weekend
  arrange(desc(gross_numeric))
joined_gross

gender_gross <- joined_gross %>%
  full_join(gender_total1, by = "movie_id") %>% #join previous table with table showing ratios of women to men
  select(c(1, 2, 4, 6, 11, 12, 13, 14, 15))%>% #remove extraneous columns
  arrange(desc(gross_numeric)) %>% #show in descending order
  head(n = 100) #limit to 100 rows to get only top 100 grossing movies in opening weekend
gender_gross
```

Average, minumum, and maximum ratios of women to men in the top 100 opening day gross
```{r, warning=FALSE, message=FALSE}
gender_gross %>%
  summarize(average_f = mean(ratiof))
gender_gross %>%
  arrange(desc(ratiof)) %>%
  head(n=5)
gender_gross %>%
  arrange(ratiof) %>%
  head(n=5)
```

```{r, warning=FALSE, message=FALSE}
joined_votes <- votes_table %>%
  inner_join(ratings_table, by = c("id", "title", "production_year")) %>% #join the table showing imdb ratings with the table showing votes
  filter(production_year > 1999) %>% #filter show only showing movies released in 2000 or later
  rename(movie_id = id) %>%
  arrange(desc(rating)) #arrange from highest to lowest rating
```

```{r gender ratings, warning=FALSE, message=FALSE}
gendervotes <- joined_votes %>%
  inner_join(gender_total1, by ="movie_id") %>% #join table with votes and ratings with table with ratio of women to men
  head(n = 100) #show top 100 rated movies
gendervotes
```

Average, minumum, and maximum ratios of women to men in the top 100 ratings
```{r}
gendervotes %>%
  summarize(average_f = mean(ratiof))
gendervotes %>%
  arrange(desc(ratiof)) %>%
  head(n=5)
gendervotes %>%
  arrange(ratiof) %>%
  head(n=5)
```

